#!/bin/bash
#
# Compare directories checking filenames and sizes
#

case_indep="no"
use_size="no"
fmtstr="%n"

while [ $# -gt 0 ]; do
   case $1 in
      -i) case_indep="yes";;
      -s) use_size="yes";;
      -h|--help) shift $#;;
      --) shift; break;;
      -*) echo "$(basename $0): invalid option '$1'" >&2; exit 1;;
      *) break;;
   esac
   shift
done

if [ $# -ne 2 ]; then
   echo "usage: $(basename $0) [-i] [-s] DIR1 DIR2"
   exit 1
fi

[ $use_size = "yes" ] && fmtstr="$fmtstr %s"

if [ $case_indep ]; then
   casefunc() { tr [:upper:] [:lower:]; }
else
   casefunc() { cat; }
fi

dir1=$1
dir2=$2

diff <(cd "$dir1"; find . \! -type d -exec stat -c "$fmtstr" {} \; \
        | sort | casefunc) \
     <(cd "$dir2"; find . \! -type d -exec stat -c "$fmtstr" {} \; \
        | sort | casefunc) | grep '^[><]'
