#!/bin/bash
#
# Case-independent diff of directories based on file name and size
#

dir1=$1
dir2=$2

diff <(cd $dir1; find . \! -type d -exec stat -c "%n %s" {} \; | sort | tr [:upper:] [:lower:]) \
     <(cd $dir2; find . \! -type d -exec stat -c "%n %s" {} \; | sort | tr [:upper:] [:lower:])
