#!/bin/sh
#
# exifautotran [list of files]
#
# Transforms Exif files so that Orientation becomes 1
#
# unterwulf's note:
# This is an improved version of a script that was stolen
# from http://sylvana.net/jpegcrop/exif_orientation.html
#
# The differencies are:
# 1. Based on exiv2 instead of jpegexiforient
# 2. Preserves timestamps of changed files
#

for file; do
   orient=$(exiv2 -Pv -g Exif.Image.Orientation "$file")
   case $orient in
      1) transform="";;
      2) transform="-flip horizontal";;
      3) transform="-rotate 180";;
      4) transform="-flip vertical";;
      5) transform="-transpose";;
      6) transform="-rotate 90";;
      7) transform="-transverse";;
      8) transform="-rotate 270";;
      *) transform="";;
   esac
   if [ -n "$transform" ]; then
      echo Executing: jpegtran -copy all $transform "$file"
      jpegtran -copy all $transform "$file" > tempfile
      if [ $? -ne 0 ]; then
         echo Error while transforming $file - skipped.
         rm tempfile
      else
         touch -r "$file" tempfile
         mv tempfile "$file"
         exiv2 -k -M'set Exif.Image.Orientation 1' "$file"
      fi
   fi
done
