#!/bin/sh
#
# Mount FUSE filesystems by mount point using ~/.fstab file
#

FSTAB=~/.fstab

if [ $# -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   echo "usage: $(basename $0) MOUNTPOINT" >&2
   exit 1
fi

mountpoint=$(readlink -f -- "$1")
cmd=$(awk -v mp="$mountpoint" -f - -- "$FSTAB" <<"EOF"
$2 == mp {
   if ($4)
      opts = "-o " $4

   FS="#"
   $0=$1

   print $1 " " $2 " " mp " " opts
   exit
}
EOF
)

if [ -n "$cmd" ]; then
   exec $cmd
else
   echo "$(basename $0): can't find $1 in $FSTAB" >&2
fi

exit 1
