#!/bin/bash
#
# Mount FUSE filesystems by mount point using ~/.fstab file
#

IFS=$'\n'
mountpoint=$(readlink -f "$1")

for line in $(sed 's/[\t ]\+/ /' ~/.fstab); do
    IFS=' '
    set $line
    curmountpoint=$(readlink -f "$2" 2>/dev/null)
    if [ "$curmountpoint" = "$mountpoint" ]; then
        IFS='#'
        set $1
        $1 $2 $mountpoint
        exit $?
    fi
done

exit 1
