#!/bin/sh
#
# Mount FUSE filesystems by mount point using ~/.fstab file
#

# mountpoint will contain absolute mountpoint path with all backslashes
# and double-quotes escaped
mountpoint=$(readlink -f -- "$1" | sed 's/["\]/\\&/g')

fs=$(awk "{ if (\$2 == \"$mountpoint\") { print \$1; exit } }" ~/.fstab)

if [ -n "$fs" ]; then
   IFS='#'
   set $fs
   "$1" "$2" $mountpoint
   exit $?
fi

exit 1
