#!/bin/sh
#
# List photos with detailed timestamp information.
#

[ $# -eq 0 ] && set *.jpg && [ "$1" = '*.jpg' ] && exit 0

for file; do
   timestamp=$(exiv2 -Pt -g Exif.Photo.DateTimeOriginal "$file")
   : ${timestamp:="xxxx-xx-xx xx:xx:xx"}
   mtime=$(stat -c "%y" "$file")
   mtime=${mtime%.*}
   printf "%-14s %-14s %s\n" "$timestamp" "$mtime" "$file"
done
