#!/bin/sh

if [ "$1" = "--be" ]; then
   be=1
   shift
else
   be=0
fi

res=
num=$1
DIV=256

while [ $num -gt 0 ]; do
   rem=$(expr $num % $DIV)

   if [ $be -ne 0 ]; then
      res="$rem $res"
   else
      res="$res $rem"
   fi

   num=$(expr $num / $DIV)
done

echo $res
