#!/bin/sh
#
# Rename the specified files to lower or upper case
#

case ${0##*/rn} in
lower) convfn() { echo "$1" | tr '[:upper:]' '[:lower:]'; };;
upper) convfn() { echo "$1" | tr '[:lower:]' '[:upper:]'; };;
*) echo "Don't know what to do under the name ${0##*/}">&2; exit 1;;
esac

if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   echo "usage: $(basename $0) FILE..." >&2
   exit 1
fi

for file; do
   dirname=$(dirname -- "$file")
   basename=$(basename -- "$file")
   newname=$(convfn "$basename")
   if [ "$basename" = "$newname" ]; then
      # do nothing, just silently skip the file
      continue
   elif [ ! -e "$dirname/$newname" ]; then
      mv -- "$file" "$dirname/$newname"
   else
      echo "$(basename $0): '$dirname/$newname' already exists," \
           "skipping '$file'" >&2
   fi
done
