#!/bin/sh
#
# Sort raw files order in the specified directories (for silly home devices)
#

if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "usage: $(basename $0) DIR..." >&2
    exit 1
fi

for dir; do
    if [ ! -d "$dir" ]; then
        echo "$(basename $0): '$dir' doesn't exist or is not a directory" >&2
        exit 1
    fi

    srcdir=$(readlink -f -- "$dir")
    tmpdir=$srcdir.sort.$$

    mkdir "$tmpdir"

    find "$srcdir" -mindepth 1 -maxdepth 1 -xdev -print0 | sort -z | \
        xargs -0 -n 1 \
        sh -c "mv \"\$1\" \"$tmpdir\"/\"\$(basename \"\$1\")\"" sh

    rmdir "$srcdir"
    mv "$tmpdir" "$srcdir"
done
