#!/bin/sh
#
# Poll remote host until it become available or maxattemps is reached
#
# Exit status:
# 0  The host is available
# 1  The host is not available and max attempts is reached
#

maxattempts=0
delay=10

fatal()
{
   echo "$(basename $0): $*" >&2
   exit 1
}

while [ $# -gt 0 ]; do
   case $1 in
      -m) shift; maxattempts=$1;;
      -d) shift; delay=$1;;
      -h|--help) shift $#;;
      --) shift; break;;
      -*) fatal "invalid option '$1'";;
      *)  break;;
   esac
   shift
done

if [ $# -ne 1 ]; then
   echo "usage: $(basename $0) [-m MAX] [-d DELAY] HOST" >&2
   exit 1
fi

host=$1
attempt=1

while :; do
   ping -q -c 4 "$host" >/dev/null 2>&1 && exit 0
   attempt=$(expr $attempt + 1)
   [ $maxattempts -ne 0 ] && [ $attempt -gt $maxattempts ] && break
   sleep $delay
done

fatal "host $host has not become available"
