#!/bin/sh
#
# Poll remote host and execute the command if the host is reacheable
#

maxattempts=0
delay=10

while [ $# -gt 1 ]; do
   case $1 in
      -m)
         maxattempts=$2
         shift 2
         ;;
      -d)
         delay=$2
         shift 2
         ;;
      --)
         shift 1
         break
         ;;
      *)
         break
         ;;
   esac
done

if [ $# -lt 2 ]; then
   echo "usage: $(basename $0) [-m MAX] [-d DELAY] HOST CMD" >&2
   exit 1
fi

host=$1
shift
attempt=1

while [ 1 ]; do
   ping -q -c 4 "$host" >/dev/null 2>&1
   retval=$?
   if [ $retval -eq 0 ]; then
      "$@"
      exit $?
   fi
   attempt=$(echo $attempt+1 | bc)
   if [ $maxattempts -ne 0 ] || [ $attempt -gt $maxattempts ]; then
      break
   fi
   sleep $delay
done
